name: regression

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '38 7 * * 6'

jobs:
  address-sanitize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++ cmake ninja-build

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=address -DCMAKE_CXX_COMPILER=g++ -DCXX_STANDARD_UPTO=23 -G Ninja ..

    - name: Build
      working-directory: build
      run: ninja unit_test

    - name: Run unit test
      working-directory: build
      run: ctest --output-on-failure

  undefined-behavior-sanitize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++ cmake ninja-build

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=undefined -DCMAKE_CXX_COMPILER=g++ -DCXX_STANDARD_UPTO=23 -G Ninja ..

    - name: Build
      working-directory: build
      run: ninja unit_test

    - name: Run unit test
      working-directory: build
      run: ctest --output-on-failure

  gcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++ cmake ninja-build

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DCXX_STANDARD_UPTO=23 -G Ninja ..

    - name: Build
      working-directory: build
      run: ninja unit_test

    - name: Run unit test
      working-directory: build
      run: ctest --output-on-failure

  clang:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends clang cmake ninja-build

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCXX_STANDARD_UPTO=23 -G Ninja ..

    - name: Build
      working-directory: build
      run: ninja unit_test

    - name: Run unit test
      working-directory: build
      run: ctest --output-on-failure
